<?php

// Code generated by make sdkversions. DO NOT EDIT.
//
// Bumped only by the release workflow, which checks the API serves it first.

namespace Jamm;

/** The Jamm API version this SDK was built against. */
final class ApiVersion
{
    public const VALUE = '2026-08-26';
}
