<?php
/**
 * ChargeMessageApiSource
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ChargeMessageApiSource Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChargeMessageApiSource
{
    /**
     * Possible values of this enum
     */
    public const API_SOURCE_UNSPECIFIED = 'API_SOURCE_UNSPECIFIED';

    public const API_SOURCE_OFF_SESSION_SYNC = 'API_SOURCE_OFF_SESSION_SYNC';

    public const API_SOURCE_OFF_SESSION_ASYNC = 'API_SOURCE_OFF_SESSION_ASYNC';

    public const API_SOURCE_ON_SESSION = 'API_SOURCE_ON_SESSION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::API_SOURCE_UNSPECIFIED,
            self::API_SOURCE_OFF_SESSION_SYNC,
            self::API_SOURCE_OFF_SESSION_ASYNC,
            self::API_SOURCE_ON_SESSION
        ];
    }
}


