<?php
/**
 * V1AsyncStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1AsyncStatus Class Doc Comment
 *
 * @category Class
 * @description AsyncStatus represents the status of an asynchronous operation.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1AsyncStatus
{
    /**
     * Possible values of this enum
     */
    public const ASYNC_STATUS_UNSPECIFIED = 'ASYNC_STATUS_UNSPECIFIED';

    public const ASYNC_STATUS_PENDING = 'ASYNC_STATUS_PENDING';

    public const ASYNC_STATUS_RUNNING = 'ASYNC_STATUS_RUNNING';

    public const ASYNC_STATUS_SUCCEEDED = 'ASYNC_STATUS_SUCCEEDED';

    public const ASYNC_STATUS_FAILED_TO_START = 'ASYNC_STATUS_FAILED_TO_START';

    public const ASYNC_STATUS_FAILED = 'ASYNC_STATUS_FAILED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ASYNC_STATUS_UNSPECIFIED,
            self::ASYNC_STATUS_PENDING,
            self::ASYNC_STATUS_RUNNING,
            self::ASYNC_STATUS_SUCCEEDED,
            self::ASYNC_STATUS_FAILED_TO_START,
            self::ASYNC_STATUS_FAILED
        ];
    }
}


