<?php
/**
 * V1Bank
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1Bank Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1Bank implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v1Bank';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'code' => 'string',
        'name' => 'string',
        'name_katakana' => 'string',
        'name_hiragana' => 'string',
        'name_alphabet' => 'string',
        'assets' => '\OpenAPI\Client\Model\V1BankAssets',
        'quota' => '\OpenAPI\Client\Model\V1BankQuota',
        'opening_hours' => 'string',
        'bankpay_scheduled_maintenances' => '\OpenAPI\Client\Model\V1BankScheduledMaintenancePeriod[]',
        'bank_scheduled_maintenances' => '\OpenAPI\Client\Model\V1BankScheduledMaintenancePeriod[]',
        'registration_scheduled_maintenances' => '\OpenAPI\Client\Model\V1BankScheduledMaintenancePeriod[]',
        'bankpay_available' => 'bool',
        'bank_available' => 'bool',
        'registration_available' => 'bool',
        'operating' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'code' => null,
        'name' => null,
        'name_katakana' => null,
        'name_hiragana' => null,
        'name_alphabet' => null,
        'assets' => null,
        'quota' => null,
        'opening_hours' => null,
        'bankpay_scheduled_maintenances' => null,
        'bank_scheduled_maintenances' => null,
        'registration_scheduled_maintenances' => null,
        'bankpay_available' => null,
        'bank_available' => null,
        'registration_available' => null,
        'operating' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'code' => false,
        'name' => false,
        'name_katakana' => false,
        'name_hiragana' => false,
        'name_alphabet' => false,
        'assets' => false,
        'quota' => false,
        'opening_hours' => false,
        'bankpay_scheduled_maintenances' => false,
        'bank_scheduled_maintenances' => false,
        'registration_scheduled_maintenances' => false,
        'bankpay_available' => false,
        'bank_available' => false,
        'registration_available' => false,
        'operating' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'name' => 'name',
        'name_katakana' => 'nameKatakana',
        'name_hiragana' => 'nameHiragana',
        'name_alphabet' => 'nameAlphabet',
        'assets' => 'assets',
        'quota' => 'quota',
        'opening_hours' => 'openingHours',
        'bankpay_scheduled_maintenances' => 'bankpayScheduledMaintenances',
        'bank_scheduled_maintenances' => 'bankScheduledMaintenances',
        'registration_scheduled_maintenances' => 'registrationScheduledMaintenances',
        'bankpay_available' => 'bankpayAvailable',
        'bank_available' => 'bankAvailable',
        'registration_available' => 'registrationAvailable',
        'operating' => 'operating'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'name' => 'setName',
        'name_katakana' => 'setNameKatakana',
        'name_hiragana' => 'setNameHiragana',
        'name_alphabet' => 'setNameAlphabet',
        'assets' => 'setAssets',
        'quota' => 'setQuota',
        'opening_hours' => 'setOpeningHours',
        'bankpay_scheduled_maintenances' => 'setBankpayScheduledMaintenances',
        'bank_scheduled_maintenances' => 'setBankScheduledMaintenances',
        'registration_scheduled_maintenances' => 'setRegistrationScheduledMaintenances',
        'bankpay_available' => 'setBankpayAvailable',
        'bank_available' => 'setBankAvailable',
        'registration_available' => 'setRegistrationAvailable',
        'operating' => 'setOperating'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'name' => 'getName',
        'name_katakana' => 'getNameKatakana',
        'name_hiragana' => 'getNameHiragana',
        'name_alphabet' => 'getNameAlphabet',
        'assets' => 'getAssets',
        'quota' => 'getQuota',
        'opening_hours' => 'getOpeningHours',
        'bankpay_scheduled_maintenances' => 'getBankpayScheduledMaintenances',
        'bank_scheduled_maintenances' => 'getBankScheduledMaintenances',
        'registration_scheduled_maintenances' => 'getRegistrationScheduledMaintenances',
        'bankpay_available' => 'getBankpayAvailable',
        'bank_available' => 'getBankAvailable',
        'registration_available' => 'getRegistrationAvailable',
        'operating' => 'getOperating'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('name_katakana', $data ?? [], null);
        $this->setIfExists('name_hiragana', $data ?? [], null);
        $this->setIfExists('name_alphabet', $data ?? [], null);
        $this->setIfExists('assets', $data ?? [], null);
        $this->setIfExists('quota', $data ?? [], null);
        $this->setIfExists('opening_hours', $data ?? [], null);
        $this->setIfExists('bankpay_scheduled_maintenances', $data ?? [], null);
        $this->setIfExists('bank_scheduled_maintenances', $data ?? [], null);
        $this->setIfExists('registration_scheduled_maintenances', $data ?? [], null);
        $this->setIfExists('bankpay_available', $data ?? [], null);
        $this->setIfExists('bank_available', $data ?? [], null);
        $this->setIfExists('registration_available', $data ?? [], null);
        $this->setIfExists('operating', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code code
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets name_katakana
     *
     * @return string|null
     */
    public function getNameKatakana()
    {
        return $this->container['name_katakana'];
    }

    /**
     * Sets name_katakana
     *
     * @param string|null $name_katakana name_katakana
     *
     * @return self
     */
    public function setNameKatakana($name_katakana)
    {
        if (is_null($name_katakana)) {
            throw new \InvalidArgumentException('non-nullable name_katakana cannot be null');
        }
        $this->container['name_katakana'] = $name_katakana;

        return $this;
    }

    /**
     * Gets name_hiragana
     *
     * @return string|null
     */
    public function getNameHiragana()
    {
        return $this->container['name_hiragana'];
    }

    /**
     * Sets name_hiragana
     *
     * @param string|null $name_hiragana name_hiragana
     *
     * @return self
     */
    public function setNameHiragana($name_hiragana)
    {
        if (is_null($name_hiragana)) {
            throw new \InvalidArgumentException('non-nullable name_hiragana cannot be null');
        }
        $this->container['name_hiragana'] = $name_hiragana;

        return $this;
    }

    /**
     * Gets name_alphabet
     *
     * @return string|null
     */
    public function getNameAlphabet()
    {
        return $this->container['name_alphabet'];
    }

    /**
     * Sets name_alphabet
     *
     * @param string|null $name_alphabet name_alphabet
     *
     * @return self
     */
    public function setNameAlphabet($name_alphabet)
    {
        if (is_null($name_alphabet)) {
            throw new \InvalidArgumentException('non-nullable name_alphabet cannot be null');
        }
        $this->container['name_alphabet'] = $name_alphabet;

        return $this;
    }

    /**
     * Gets assets
     *
     * @return \OpenAPI\Client\Model\V1BankAssets|null
     */
    public function getAssets()
    {
        return $this->container['assets'];
    }

    /**
     * Sets assets
     *
     * @param \OpenAPI\Client\Model\V1BankAssets|null $assets assets
     *
     * @return self
     */
    public function setAssets($assets)
    {
        if (is_null($assets)) {
            throw new \InvalidArgumentException('non-nullable assets cannot be null');
        }
        $this->container['assets'] = $assets;

        return $this;
    }

    /**
     * Gets quota
     *
     * @return \OpenAPI\Client\Model\V1BankQuota|null
     */
    public function getQuota()
    {
        return $this->container['quota'];
    }

    /**
     * Sets quota
     *
     * @param \OpenAPI\Client\Model\V1BankQuota|null $quota quota
     *
     * @return self
     */
    public function setQuota($quota)
    {
        if (is_null($quota)) {
            throw new \InvalidArgumentException('non-nullable quota cannot be null');
        }
        $this->container['quota'] = $quota;

        return $this;
    }

    /**
     * Gets opening_hours
     *
     * @return string|null
     */
    public function getOpeningHours()
    {
        return $this->container['opening_hours'];
    }

    /**
     * Sets opening_hours
     *
     * @param string|null $opening_hours opening_hours
     *
     * @return self
     */
    public function setOpeningHours($opening_hours)
    {
        if (is_null($opening_hours)) {
            throw new \InvalidArgumentException('non-nullable opening_hours cannot be null');
        }
        $this->container['opening_hours'] = $opening_hours;

        return $this;
    }

    /**
     * Gets bankpay_scheduled_maintenances
     *
     * @return \OpenAPI\Client\Model\V1BankScheduledMaintenancePeriod[]|null
     */
    public function getBankpayScheduledMaintenances()
    {
        return $this->container['bankpay_scheduled_maintenances'];
    }

    /**
     * Sets bankpay_scheduled_maintenances
     *
     * @param \OpenAPI\Client\Model\V1BankScheduledMaintenancePeriod[]|null $bankpay_scheduled_maintenances bankpay_scheduled_maintenances
     *
     * @return self
     */
    public function setBankpayScheduledMaintenances($bankpay_scheduled_maintenances)
    {
        if (is_null($bankpay_scheduled_maintenances)) {
            throw new \InvalidArgumentException('non-nullable bankpay_scheduled_maintenances cannot be null');
        }
        $this->container['bankpay_scheduled_maintenances'] = $bankpay_scheduled_maintenances;

        return $this;
    }

    /**
     * Gets bank_scheduled_maintenances
     *
     * @return \OpenAPI\Client\Model\V1BankScheduledMaintenancePeriod[]|null
     */
    public function getBankScheduledMaintenances()
    {
        return $this->container['bank_scheduled_maintenances'];
    }

    /**
     * Sets bank_scheduled_maintenances
     *
     * @param \OpenAPI\Client\Model\V1BankScheduledMaintenancePeriod[]|null $bank_scheduled_maintenances bank_scheduled_maintenances
     *
     * @return self
     */
    public function setBankScheduledMaintenances($bank_scheduled_maintenances)
    {
        if (is_null($bank_scheduled_maintenances)) {
            throw new \InvalidArgumentException('non-nullable bank_scheduled_maintenances cannot be null');
        }
        $this->container['bank_scheduled_maintenances'] = $bank_scheduled_maintenances;

        return $this;
    }

    /**
     * Gets registration_scheduled_maintenances
     *
     * @return \OpenAPI\Client\Model\V1BankScheduledMaintenancePeriod[]|null
     */
    public function getRegistrationScheduledMaintenances()
    {
        return $this->container['registration_scheduled_maintenances'];
    }

    /**
     * Sets registration_scheduled_maintenances
     *
     * @param \OpenAPI\Client\Model\V1BankScheduledMaintenancePeriod[]|null $registration_scheduled_maintenances registration_scheduled_maintenances
     *
     * @return self
     */
    public function setRegistrationScheduledMaintenances($registration_scheduled_maintenances)
    {
        if (is_null($registration_scheduled_maintenances)) {
            throw new \InvalidArgumentException('non-nullable registration_scheduled_maintenances cannot be null');
        }
        $this->container['registration_scheduled_maintenances'] = $registration_scheduled_maintenances;

        return $this;
    }

    /**
     * Gets bankpay_available
     *
     * @return bool|null
     */
    public function getBankpayAvailable()
    {
        return $this->container['bankpay_available'];
    }

    /**
     * Sets bankpay_available
     *
     * @param bool|null $bankpay_available True when Bankpay is currently available.
     *
     * @return self
     */
    public function setBankpayAvailable($bankpay_available)
    {
        if (is_null($bankpay_available)) {
            throw new \InvalidArgumentException('non-nullable bankpay_available cannot be null');
        }
        $this->container['bankpay_available'] = $bankpay_available;

        return $this;
    }

    /**
     * Gets bank_available
     *
     * @return bool|null
     */
    public function getBankAvailable()
    {
        return $this->container['bank_available'];
    }

    /**
     * Sets bank_available
     *
     * @param bool|null $bank_available True when Bank is currently available.
     *
     * @return self
     */
    public function setBankAvailable($bank_available)
    {
        if (is_null($bank_available)) {
            throw new \InvalidArgumentException('non-nullable bank_available cannot be null');
        }
        $this->container['bank_available'] = $bank_available;

        return $this;
    }

    /**
     * Gets registration_available
     *
     * @return bool|null
     */
    public function getRegistrationAvailable()
    {
        return $this->container['registration_available'];
    }

    /**
     * Sets registration_available
     *
     * @param bool|null $registration_available True when registration is currently available.
     *
     * @return self
     */
    public function setRegistrationAvailable($registration_available)
    {
        if (is_null($registration_available)) {
            throw new \InvalidArgumentException('non-nullable registration_available cannot be null');
        }
        $this->container['registration_available'] = $registration_available;

        return $this;
    }

    /**
     * Gets operating
     *
     * @return bool|null
     */
    public function getOperating()
    {
        return $this->container['operating'];
    }

    /**
     * Sets operating
     *
     * @param bool|null $operating True when bank is operating, false when its not. Core UI is expected to navigate user to out-of-service page when this flag is set to false.  See Figma for more information: https://www.figma.com/design/7cabcqjzvKl9IwzvJCuQEW/Jamm-%CE%B2-UI-design?node-id=304-11253&t=oyEUrdVtFOMV9xut-4
     *
     * @return self
     */
    public function setOperating($operating)
    {
        if (is_null($operating)) {
            throw new \InvalidArgumentException('non-nullable operating cannot be null');
        }
        $this->container['operating'] = $operating;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


