<?php
/**
 * V1Buyer
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1Buyer Class Doc Comment
 *
 * @category Class
 * @description Buyer is a representation of a customer in your e-commerce site. We require this information to process the payment.  購入者とは、あなたのECサイトの顧客を表します。 この情報は決済を処理するために必要です。
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1Buyer implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v1Buyer';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'email' => 'string',
        'force_kyc' => 'bool',
        'phone' => 'string',
        'name' => 'string',
        'katakana_last_name' => 'string',
        'katakana_first_name' => 'string',
        'address' => 'string',
        'birth_date' => 'string',
        'gender' => 'string',
        'expires_at' => '\DateTime',
        'metadata' => 'array<string,string>'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'email' => null,
        'force_kyc' => null,
        'phone' => null,
        'name' => null,
        'katakana_last_name' => null,
        'katakana_first_name' => null,
        'address' => null,
        'birth_date' => null,
        'gender' => null,
        'expires_at' => 'date-time',
        'metadata' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'email' => false,
        'force_kyc' => false,
        'phone' => false,
        'name' => false,
        'katakana_last_name' => false,
        'katakana_first_name' => false,
        'address' => false,
        'birth_date' => false,
        'gender' => false,
        'expires_at' => false,
        'metadata' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'email' => 'email',
        'force_kyc' => 'forceKyc',
        'phone' => 'phone',
        'name' => 'name',
        'katakana_last_name' => 'katakanaLastName',
        'katakana_first_name' => 'katakanaFirstName',
        'address' => 'address',
        'birth_date' => 'birthDate',
        'gender' => 'gender',
        'expires_at' => 'expiresAt',
        'metadata' => 'metadata'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'email' => 'setEmail',
        'force_kyc' => 'setForceKyc',
        'phone' => 'setPhone',
        'name' => 'setName',
        'katakana_last_name' => 'setKatakanaLastName',
        'katakana_first_name' => 'setKatakanaFirstName',
        'address' => 'setAddress',
        'birth_date' => 'setBirthDate',
        'gender' => 'setGender',
        'expires_at' => 'setExpiresAt',
        'metadata' => 'setMetadata'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'email' => 'getEmail',
        'force_kyc' => 'getForceKyc',
        'phone' => 'getPhone',
        'name' => 'getName',
        'katakana_last_name' => 'getKatakanaLastName',
        'katakana_first_name' => 'getKatakanaFirstName',
        'address' => 'getAddress',
        'birth_date' => 'getBirthDate',
        'gender' => 'getGender',
        'expires_at' => 'getExpiresAt',
        'metadata' => 'getMetadata'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('force_kyc', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('katakana_last_name', $data ?? [], null);
        $this->setIfExists('katakana_first_name', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('birth_date', $data ?? [], null);
        $this->setIfExists('gender', $data ?? [], null);
        $this->setIfExists('expires_at', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Email of the customer. You can update this value later through the UpdateCustomer endpoint.  Customerのメールアドレス。 この値は UpdateCustomer エンドポイントを通じて後で更新できます。
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets force_kyc
     *
     * @return bool|null
     */
    public function getForceKyc()
    {
        return $this->container['force_kyc'];
    }

    /**
     * Sets force_kyc
     *
     * @param bool|null $force_kyc A flag whether Jamm to force KYC for the customer.  初回購入時に購入者に対してKYCを強制するかどうかのフラグです。
     *
     * @return self
     */
    public function setForceKyc($force_kyc)
    {
        if (is_null($force_kyc)) {
            throw new \InvalidArgumentException('non-nullable force_kyc cannot be null');
        }
        $this->container['force_kyc'] = $force_kyc;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone Phone number of the customer. You can update this value later through the UpdateCustomer endpoint. Accepts Japanese phone numbers (10-11 digits). Note that only mobile numbers (070/080/090) will be stored; non-mobile numbers are silently ignored.  e.g. - 09012345678 (mobile) - 08012345678 (mobile) - 07012345678 (mobile) - 05012345678 (IP phone, not stored) - 0312345678  (landline, not stored)  Customerの電話番号。 この値は UpdateCustomer エンドポイントを通じて後で更新できます。 携帯電話番号（070/080/090）のみ保存され、それ以外の番号は無視されます。
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Name of the customer. You can update this value later through the UpdateCustomer endpoint.  e.g. - John Appleseed - 山田太郎  購入者の氏名。 この値は UpdateCustomer エンドポイントを通じて後で更新できます。
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets katakana_last_name
     *
     * @return string|null
     */
    public function getKatakanaLastName()
    {
        return $this->container['katakana_last_name'];
    }

    /**
     * Sets katakana_last_name
     *
     * @param string|null $katakana_last_name Katakana name of the customer. You can update this value later through the UpdateCustomer endpoint.  e.g. ヤマダ  Customerのカタカナ(姓)。 この値は UpdateCustomer エンドポイントを通じて後で更新できます。
     *
     * @return self
     */
    public function setKatakanaLastName($katakana_last_name)
    {
        if (is_null($katakana_last_name)) {
            throw new \InvalidArgumentException('non-nullable katakana_last_name cannot be null');
        }
        $this->container['katakana_last_name'] = $katakana_last_name;

        return $this;
    }

    /**
     * Gets katakana_first_name
     *
     * @return string|null
     */
    public function getKatakanaFirstName()
    {
        return $this->container['katakana_first_name'];
    }

    /**
     * Sets katakana_first_name
     *
     * @param string|null $katakana_first_name Katakana name of the customer. You can update this value later through the UpdateCustomer endpoint.  e.g. タロウ  Customerのカタカナ(名)。 この値は UpdateCustomer エンドポイントを通じて後で更新できます。
     *
     * @return self
     */
    public function setKatakanaFirstName($katakana_first_name)
    {
        if (is_null($katakana_first_name)) {
            throw new \InvalidArgumentException('non-nullable katakana_first_name cannot be null');
        }
        $this->container['katakana_first_name'] = $katakana_first_name;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address Address of the customer. You can update this value later through the UpdateCustomer endpoint.  e.g. - 東京都港区六本木1-1-1  Customerの住所。 この値は UpdateCustomer エンドポイントを通じて後で更新できます。
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets birth_date
     *
     * @return string|null
     */
    public function getBirthDate()
    {
        return $this->container['birth_date'];
    }

    /**
     * Sets birth_date
     *
     * @param string|null $birth_date Birth date of the customer. You can update this value later through the UpdateCustomer endpoint.  e.g. - 1990-01-01  Customerの生年月日。 この値は UpdateCustomer エンドポイントを通じて後で更新できます。
     *
     * @return self
     */
    public function setBirthDate($birth_date)
    {
        if (is_null($birth_date)) {
            throw new \InvalidArgumentException('non-nullable birth_date cannot be null');
        }
        $this->container['birth_date'] = $birth_date;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return string|null
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param string|null $gender Gender of the customer.  Customerの性別。
     *
     * @return self
     */
    public function setGender($gender)
    {
        if (is_null($gender)) {
            throw new \InvalidArgumentException('non-nullable gender cannot be null');
        }
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets expires_at
     *
     * @return \DateTime|null
     */
    public function getExpiresAt()
    {
        return $this->container['expires_at'];
    }

    /**
     * Sets expires_at
     *
     * @param \DateTime|null $expires_at Merchant can optionally set the expiry date for the contract. Defaults to 90 minutes if not specified.  決済の有効期限。未指定の場合は90分後に自動失効します。
     *
     * @return self
     */
    public function setExpiresAt($expires_at)
    {
        if (is_null($expires_at)) {
            throw new \InvalidArgumentException('non-nullable expires_at cannot be null');
        }
        $this->container['expires_at'] = $expires_at;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,string>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,string>|null $metadata Arbitrary key-value additional information about the customer. You can see this information in our merchant dashboard.  Customerに関する任意のキーと値の追加情報。 加盟店ダッシュボードで確認できます。
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


