<?php
/**
 * V1ChargeMessage
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1ChargeMessage Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1ChargeMessage implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v1ChargeMessage';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'customer' => 'string',
        'status' => '\OpenAPI\Client\Model\V1ChargeMessageStatus',
        'description' => 'string',
        'merchant_name' => 'string',
        'initial_amount' => 'int',
        'discount' => 'int',
        'final_amount' => 'int',
        'amount_refunded' => 'int',
        'currency' => 'string',
        'processed_at' => 'string',
        'jamm_fee' => 'int',
        'created_at' => 'string',
        'updated_at' => 'string',
        'original_transaction_jamm_fee' => 'string',
        'consumption_tax' => 'int',
        'error' => '\OpenAPI\Client\Model\Apiv1Error',
        'refund_id' => 'string',
        'refund' => '\OpenAPI\Client\Model\V1RefundInfo',
        'api_source' => '\OpenAPI\Client\Model\ChargeMessageApiSource'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'customer' => null,
        'status' => null,
        'description' => null,
        'merchant_name' => null,
        'initial_amount' => 'int32',
        'discount' => 'int32',
        'final_amount' => 'int32',
        'amount_refunded' => 'int32',
        'currency' => null,
        'processed_at' => null,
        'jamm_fee' => 'int32',
        'created_at' => null,
        'updated_at' => null,
        'original_transaction_jamm_fee' => null,
        'consumption_tax' => 'int32',
        'error' => null,
        'refund_id' => null,
        'refund' => null,
        'api_source' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'customer' => false,
        'status' => false,
        'description' => false,
        'merchant_name' => false,
        'initial_amount' => false,
        'discount' => false,
        'final_amount' => false,
        'amount_refunded' => false,
        'currency' => false,
        'processed_at' => false,
        'jamm_fee' => false,
        'created_at' => false,
        'updated_at' => false,
        'original_transaction_jamm_fee' => false,
        'consumption_tax' => false,
        'error' => false,
        'refund_id' => false,
        'refund' => false,
        'api_source' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'customer' => 'customer',
        'status' => 'status',
        'description' => 'description',
        'merchant_name' => 'merchantName',
        'initial_amount' => 'initialAmount',
        'discount' => 'discount',
        'final_amount' => 'finalAmount',
        'amount_refunded' => 'amountRefunded',
        'currency' => 'currency',
        'processed_at' => 'processedAt',
        'jamm_fee' => 'jammFee',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'original_transaction_jamm_fee' => 'originalTransactionJammFee',
        'consumption_tax' => 'consumptionTax',
        'error' => 'error',
        'refund_id' => 'refundId',
        'refund' => 'refund',
        'api_source' => 'apiSource'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'customer' => 'setCustomer',
        'status' => 'setStatus',
        'description' => 'setDescription',
        'merchant_name' => 'setMerchantName',
        'initial_amount' => 'setInitialAmount',
        'discount' => 'setDiscount',
        'final_amount' => 'setFinalAmount',
        'amount_refunded' => 'setAmountRefunded',
        'currency' => 'setCurrency',
        'processed_at' => 'setProcessedAt',
        'jamm_fee' => 'setJammFee',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'original_transaction_jamm_fee' => 'setOriginalTransactionJammFee',
        'consumption_tax' => 'setConsumptionTax',
        'error' => 'setError',
        'refund_id' => 'setRefundId',
        'refund' => 'setRefund',
        'api_source' => 'setApiSource'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'customer' => 'getCustomer',
        'status' => 'getStatus',
        'description' => 'getDescription',
        'merchant_name' => 'getMerchantName',
        'initial_amount' => 'getInitialAmount',
        'discount' => 'getDiscount',
        'final_amount' => 'getFinalAmount',
        'amount_refunded' => 'getAmountRefunded',
        'currency' => 'getCurrency',
        'processed_at' => 'getProcessedAt',
        'jamm_fee' => 'getJammFee',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'original_transaction_jamm_fee' => 'getOriginalTransactionJammFee',
        'consumption_tax' => 'getConsumptionTax',
        'error' => 'getError',
        'refund_id' => 'getRefundId',
        'refund' => 'getRefund',
        'api_source' => 'getApiSource'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('merchant_name', $data ?? [], null);
        $this->setIfExists('initial_amount', $data ?? [], null);
        $this->setIfExists('discount', $data ?? [], null);
        $this->setIfExists('final_amount', $data ?? [], null);
        $this->setIfExists('amount_refunded', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('processed_at', $data ?? [], null);
        $this->setIfExists('jamm_fee', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('original_transaction_jamm_fee', $data ?? [], null);
        $this->setIfExists('consumption_tax', $data ?? [], null);
        $this->setIfExists('error', $data ?? [], null);
        $this->setIfExists('refund_id', $data ?? [], null);
        $this->setIfExists('refund', $data ?? [], null);
        $this->setIfExists('api_source', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return string|null
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param string|null $customer customer
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            throw new \InvalidArgumentException('non-nullable customer cannot be null');
        }
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \OpenAPI\Client\Model\V1ChargeMessageStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \OpenAPI\Client\Model\V1ChargeMessageStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets merchant_name
     *
     * @return string|null
     */
    public function getMerchantName()
    {
        return $this->container['merchant_name'];
    }

    /**
     * Sets merchant_name
     *
     * @param string|null $merchant_name merchant_name
     *
     * @return self
     */
    public function setMerchantName($merchant_name)
    {
        if (is_null($merchant_name)) {
            throw new \InvalidArgumentException('non-nullable merchant_name cannot be null');
        }
        $this->container['merchant_name'] = $merchant_name;

        return $this;
    }

    /**
     * Gets initial_amount
     *
     * @return int|null
     */
    public function getInitialAmount()
    {
        return $this->container['initial_amount'];
    }

    /**
     * Sets initial_amount
     *
     * @param int|null $initial_amount Original charge amount before discount and before any refund is applied.
     *
     * @return self
     */
    public function setInitialAmount($initial_amount)
    {
        if (is_null($initial_amount)) {
            throw new \InvalidArgumentException('non-nullable initial_amount cannot be null');
        }
        $this->container['initial_amount'] = $initial_amount;

        return $this;
    }

    /**
     * Gets discount
     *
     * @return int|null
     */
    public function getDiscount()
    {
        return $this->container['discount'];
    }

    /**
     * Sets discount
     *
     * @param int|null $discount Discount amount deducted from the original charge amount.
     *
     * @return self
     */
    public function setDiscount($discount)
    {
        if (is_null($discount)) {
            throw new \InvalidArgumentException('non-nullable discount cannot be null');
        }
        $this->container['discount'] = $discount;

        return $this;
    }

    /**
     * Gets final_amount
     *
     * @return int|null
     */
    public function getFinalAmount()
    {
        return $this->container['final_amount'];
    }

    /**
     * Sets final_amount
     *
     * @param int|null $final_amount Final charge amount after discount, before any refund is applied.
     *
     * @return self
     */
    public function setFinalAmount($final_amount)
    {
        if (is_null($final_amount)) {
            throw new \InvalidArgumentException('non-nullable final_amount cannot be null');
        }
        $this->container['final_amount'] = $final_amount;

        return $this;
    }

    /**
     * Gets amount_refunded
     *
     * @return int|null
     */
    public function getAmountRefunded()
    {
        return $this->container['amount_refunded'];
    }

    /**
     * Sets amount_refunded
     *
     * @param int|null $amount_refunded Total amount refunded for this charge when the charge has been refunded.
     *
     * @return self
     */
    public function setAmountRefunded($amount_refunded)
    {
        if (is_null($amount_refunded)) {
            throw new \InvalidArgumentException('non-nullable amount_refunded cannot be null');
        }
        $this->container['amount_refunded'] = $amount_refunded;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string|null $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets processed_at
     *
     * @return string|null
     */
    public function getProcessedAt()
    {
        return $this->container['processed_at'];
    }

    /**
     * Sets processed_at
     *
     * @param string|null $processed_at Timestamp when the charge or refund outcome was completed.
     *
     * @return self
     */
    public function setProcessedAt($processed_at)
    {
        if (is_null($processed_at)) {
            throw new \InvalidArgumentException('non-nullable processed_at cannot be null');
        }
        $this->container['processed_at'] = $processed_at;

        return $this;
    }

    /**
     * Gets jamm_fee
     *
     * @return int|null
     */
    public function getJammFee()
    {
        return $this->container['jamm_fee'];
    }

    /**
     * Sets jamm_fee
     *
     * @param int|null $jamm_fee Jamm fee associated with this refund event (refund uses refund fee; cancel uses 0).
     *
     * @return self
     */
    public function setJammFee($jamm_fee)
    {
        if (is_null($jamm_fee)) {
            throw new \InvalidArgumentException('non-nullable jamm_fee cannot be null');
        }
        $this->container['jamm_fee'] = $jamm_fee;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return string|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param string|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets original_transaction_jamm_fee
     *
     * @return string|null
     */
    public function getOriginalTransactionJammFee()
    {
        return $this->container['original_transaction_jamm_fee'];
    }

    /**
     * Sets original_transaction_jamm_fee
     *
     * @param string|null $original_transaction_jamm_fee Whether the original transaction's Jamm fee was waived (same-day cancel) or not (refund). Values: \"waived\", \"not_waived\".
     *
     * @return self
     */
    public function setOriginalTransactionJammFee($original_transaction_jamm_fee)
    {
        if (is_null($original_transaction_jamm_fee)) {
            throw new \InvalidArgumentException('non-nullable original_transaction_jamm_fee cannot be null');
        }
        $this->container['original_transaction_jamm_fee'] = $original_transaction_jamm_fee;

        return $this;
    }

    /**
     * Gets consumption_tax
     *
     * @return int|null
     */
    public function getConsumptionTax()
    {
        return $this->container['consumption_tax'];
    }

    /**
     * Sets consumption_tax
     *
     * @param int|null $consumption_tax Consumption tax (10% of the Jamm fee).
     *
     * @return self
     */
    public function setConsumptionTax($consumption_tax)
    {
        if (is_null($consumption_tax)) {
            throw new \InvalidArgumentException('non-nullable consumption_tax cannot be null');
        }
        $this->container['consumption_tax'] = $consumption_tax;

        return $this;
    }

    /**
     * Gets error
     *
     * @return \OpenAPI\Client\Model\Apiv1Error|null
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param \OpenAPI\Client\Model\Apiv1Error|null $error error
     *
     * @return self
     */
    public function setError($error)
    {
        if (is_null($error)) {
            throw new \InvalidArgumentException('non-nullable error cannot be null');
        }
        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Gets refund_id
     *
     * @return string|null
     */
    public function getRefundId()
    {
        return $this->container['refund_id'];
    }

    /**
     * Sets refund_id
     *
     * @param string|null $refund_id External refund identifier (rfd-*) for refund/refund-failed webhooks.
     *
     * @return self
     */
    public function setRefundId($refund_id)
    {
        if (is_null($refund_id)) {
            throw new \InvalidArgumentException('non-nullable refund_id cannot be null');
        }
        $this->container['refund_id'] = $refund_id;

        return $this;
    }

    /**
     * Gets refund
     *
     * @return \OpenAPI\Client\Model\V1RefundInfo|null
     */
    public function getRefund()
    {
        return $this->container['refund'];
    }

    /**
     * Sets refund
     *
     * @param \OpenAPI\Client\Model\V1RefundInfo|null $refund refund
     *
     * @return self
     */
    public function setRefund($refund)
    {
        if (is_null($refund)) {
            throw new \InvalidArgumentException('non-nullable refund cannot be null');
        }
        $this->container['refund'] = $refund;

        return $this;
    }

    /**
     * Gets api_source
     *
     * @return \OpenAPI\Client\Model\ChargeMessageApiSource|null
     */
    public function getApiSource()
    {
        return $this->container['api_source'];
    }

    /**
     * Sets api_source
     *
     * @param \OpenAPI\Client\Model\ChargeMessageApiSource|null $api_source api_source
     *
     * @return self
     */
    public function setApiSource($api_source)
    {
        if (is_null($api_source)) {
            throw new \InvalidArgumentException('non-nullable api_source cannot be null');
        }
        $this->container['api_source'] = $api_source;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


