<?php
/**
 * V1ChargeStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1ChargeStatus Class Doc Comment
 *
 * @category Class
 * @description ChargeStatus represents the status of a charge transaction.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1ChargeStatus
{
    /**
     * Possible values of this enum
     */
    public const CHARGE_STATUS_UNSPECIFIED = 'CHARGE_STATUS_UNSPECIFIED';

    public const CHARGE_STATUS_SUCCESS = 'CHARGE_STATUS_SUCCESS';

    public const CHARGE_STATUS_FAILURE = 'CHARGE_STATUS_FAILURE';

    public const CHARGE_STATUS_WAITING_EKYC = 'CHARGE_STATUS_WAITING_EKYC';

    public const CHARGE_STATUS_BLOCKING = 'CHARGE_STATUS_BLOCKING';

    public const CHARGE_STATUS_CANCELLED = 'CHARGE_STATUS_CANCELLED';

    public const CHARGE_STATUS_REFUNDED = 'CHARGE_STATUS_REFUNDED';

    public const CHARGE_STATUS_PENDING = 'CHARGE_STATUS_PENDING';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CHARGE_STATUS_UNSPECIFIED,
            self::CHARGE_STATUS_SUCCESS,
            self::CHARGE_STATUS_FAILURE,
            self::CHARGE_STATUS_WAITING_EKYC,
            self::CHARGE_STATUS_BLOCKING,
            self::CHARGE_STATUS_CANCELLED,
            self::CHARGE_STATUS_REFUNDED,
            self::CHARGE_STATUS_PENDING
        ];
    }
}


