<?php
/**
 * V1ChargeMessageStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1ChargeMessageStatus Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1ChargeMessageStatus
{
    /**
     * Possible values of this enum
     */
    public const STATUS_UNSPECIFIED = 'STATUS_UNSPECIFIED';

    public const STATUS_SUCCESS = 'STATUS_SUCCESS';

    public const STATUS_FAILURE = 'STATUS_FAILURE';

    public const STATUS_WAITING_EKYC = 'STATUS_WAITING_EKYC';

    public const STATUS_BLOCKING = 'STATUS_BLOCKING';

    public const STATUS_CANCELLED = 'STATUS_CANCELLED';

    public const STATUS_REFUNDED = 'STATUS_REFUNDED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::STATUS_UNSPECIFIED,
            self::STATUS_SUCCESS,
            self::STATUS_FAILURE,
            self::STATUS_WAITING_EKYC,
            self::STATUS_BLOCKING,
            self::STATUS_CANCELLED,
            self::STATUS_REFUNDED
        ];
    }
}


