<?php
/**
 * V1ContractStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1ContractStatus Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1ContractStatus
{
    /**
     * Possible values of this enum
     */
    public const CONTRACT_STATUS_UNSPECIFIED = 'CONTRACT_STATUS_UNSPECIFIED';

    public const CONTRACT_STATUS_INITIAL = 'CONTRACT_STATUS_INITIAL';

    public const CONTRACT_STATUS_APPROVED = 'CONTRACT_STATUS_APPROVED';

    public const CONTRACT_STATUS_ACTIVATED = 'CONTRACT_STATUS_ACTIVATED';

    public const CONTRACT_STATUS_WAITING_EKYC = 'CONTRACT_STATUS_WAITING_EKYC';

    public const CONTRACT_STATUS_EXPIRED = 'CONTRACT_STATUS_EXPIRED';

    public const CONTRACT_STATUS_DEACTIVATED = 'CONTRACT_STATUS_DEACTIVATED';

    public const CONTRACT_STATUS_CANCELLED = 'CONTRACT_STATUS_CANCELLED';

    public const CONTRACT_STATUS_PENDING_CHARGE = 'CONTRACT_STATUS_PENDING_CHARGE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CONTRACT_STATUS_UNSPECIFIED,
            self::CONTRACT_STATUS_INITIAL,
            self::CONTRACT_STATUS_APPROVED,
            self::CONTRACT_STATUS_ACTIVATED,
            self::CONTRACT_STATUS_WAITING_EKYC,
            self::CONTRACT_STATUS_EXPIRED,
            self::CONTRACT_STATUS_DEACTIVATED,
            self::CONTRACT_STATUS_CANCELLED,
            self::CONTRACT_STATUS_PENDING_CHARGE
        ];
    }
}


