<?php
/**
 * V1DepositType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1DepositType Class Doc Comment
 *
 * @category Class
 * @description - DEPOSIT_TYPE_SAVINGS: 普通  - DEPOSIT_TYPE_CHECKING: 当座
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1DepositType
{
    /**
     * Possible values of this enum
     */
    public const DEPOSIT_TYPE_UNSPECIFIED = 'DEPOSIT_TYPE_UNSPECIFIED';

    public const DEPOSIT_TYPE_SAVINGS = 'DEPOSIT_TYPE_SAVINGS';

    public const DEPOSIT_TYPE_CHECKING = 'DEPOSIT_TYPE_CHECKING';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DEPOSIT_TYPE_UNSPECIFIED,
            self::DEPOSIT_TYPE_SAVINGS,
            self::DEPOSIT_TYPE_CHECKING
        ];
    }
}


