<?php
/**
 * V1EventType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1EventType Class Doc Comment
 *
 * @category Class
 * @description EventType defines the webhook events that Jamm sends to merchant endpoints. These events allow merchants to track the lifecycle of payments and contracts and take appropriate actions in their systems.   - EVENT_TYPE_UNSPECIFIED: No event type specified (default value). Merchants should ignore messages with this event type.  - EVENT_TYPE_CHARGE_CREATED: Fired when a charge is first created but not yet processed.  - EVENT_TYPE_CHARGE_UPDATED: Fired when a charge&#39;s details or status changes. Common scenarios include: - Status change after KYC approval Payload contains the updated charge details with current status.  - EVENT_TYPE_CHARGE_SUCCESS: Fired when a payment is successfully completed. Payload contains the finalized charge details including amount, currency, and transaction timestamps. Merchants should fulfill orders or provide access to purchased services.  - EVENT_TYPE_CHARGE_FAIL: Fired when a payment attempt fails for any reason. Payload contains charge details with failure information and error codes. Merchants may want to contact the customer or attempt recovery actions.  - EVENT_TYPE_CHARGE_CANCEL: Fired when a charge is canceled by the merchant. Payload contains the canceled charge details. Merchants should update their records to reflect the cancellation.  - EVENT_TYPE_CONTRACT_ACTIVATED: Fired when a contract is activated.  - EVENT_TYPE_USER_ACCOUNT_DELETED: Fired when a Jamm user account is deleted. Payload contains user account information. Merchants should update their records about this customer.  - EVENT_TYPE_TESTING: Used for testing webhook integrations and configurations. Merchants can safely ignore this in production environments.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1EventType
{
    /**
     * Possible values of this enum
     */
    public const EVENT_TYPE_UNSPECIFIED = 'EVENT_TYPE_UNSPECIFIED';

    public const EVENT_TYPE_CHARGE_CREATED = 'EVENT_TYPE_CHARGE_CREATED';

    public const EVENT_TYPE_CHARGE_UPDATED = 'EVENT_TYPE_CHARGE_UPDATED';

    public const EVENT_TYPE_CHARGE_SUCCESS = 'EVENT_TYPE_CHARGE_SUCCESS';

    public const EVENT_TYPE_CHARGE_FAIL = 'EVENT_TYPE_CHARGE_FAIL';

    public const EVENT_TYPE_CHARGE_CANCEL = 'EVENT_TYPE_CHARGE_CANCEL';

    public const EVENT_TYPE_CONTRACT_ACTIVATED = 'EVENT_TYPE_CONTRACT_ACTIVATED';

    public const EVENT_TYPE_USER_ACCOUNT_DELETED = 'EVENT_TYPE_USER_ACCOUNT_DELETED';

    public const EVENT_TYPE_TESTING = 'EVENT_TYPE_TESTING';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EVENT_TYPE_UNSPECIFIED,
            self::EVENT_TYPE_CHARGE_CREATED,
            self::EVENT_TYPE_CHARGE_UPDATED,
            self::EVENT_TYPE_CHARGE_SUCCESS,
            self::EVENT_TYPE_CHARGE_FAIL,
            self::EVENT_TYPE_CHARGE_CANCEL,
            self::EVENT_TYPE_CONTRACT_ACTIVATED,
            self::EVENT_TYPE_USER_ACCOUNT_DELETED,
            self::EVENT_TYPE_TESTING
        ];
    }
}


