<?php
/**
 * V1KycStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1KycStatus Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1KycStatus
{
    /**
     * Possible values of this enum
     */
    public const KYC_STATUS_UNSPECIFIED = 'KYC_STATUS_UNSPECIFIED';

    public const KYC_STATUS_APPROVED = 'KYC_STATUS_APPROVED';

    public const KYC_STATUS_NOT_SUBMITTED = 'KYC_STATUS_NOT_SUBMITTED';

    public const KYC_STATUS_IN_REVIEW = 'KYC_STATUS_IN_REVIEW';

    public const KYC_STATUS_DENIED = 'KYC_STATUS_DENIED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::KYC_STATUS_UNSPECIFIED,
            self::KYC_STATUS_APPROVED,
            self::KYC_STATUS_NOT_SUBMITTED,
            self::KYC_STATUS_IN_REVIEW,
            self::KYC_STATUS_DENIED
        ];
    }
}


