<?php
/**
 * V1MessageResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1MessageResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1MessageResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'v1MessageResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'merchant_webhook_message' => '\OpenAPI\Client\Model\V1MerchantWebhookMessage',
        'charge_message' => '\OpenAPI\Client\Model\V1ChargeMessage',
        'contract_message' => '\OpenAPI\Client\Model\V1ContractMessage',
        'user_account_message' => '\OpenAPI\Client\Model\V1UserAccountMessage',
        'refund_info' => '\OpenAPI\Client\Model\V1RefundInfo'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'merchant_webhook_message' => null,
        'charge_message' => null,
        'contract_message' => null,
        'user_account_message' => null,
        'refund_info' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'merchant_webhook_message' => false,
        'charge_message' => false,
        'contract_message' => false,
        'user_account_message' => false,
        'refund_info' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'merchant_webhook_message' => 'merchantWebhookMessage',
        'charge_message' => 'chargeMessage',
        'contract_message' => 'contractMessage',
        'user_account_message' => 'userAccountMessage',
        'refund_info' => 'refundInfo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'merchant_webhook_message' => 'setMerchantWebhookMessage',
        'charge_message' => 'setChargeMessage',
        'contract_message' => 'setContractMessage',
        'user_account_message' => 'setUserAccountMessage',
        'refund_info' => 'setRefundInfo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'merchant_webhook_message' => 'getMerchantWebhookMessage',
        'charge_message' => 'getChargeMessage',
        'contract_message' => 'getContractMessage',
        'user_account_message' => 'getUserAccountMessage',
        'refund_info' => 'getRefundInfo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('merchant_webhook_message', $data ?? [], null);
        $this->setIfExists('charge_message', $data ?? [], null);
        $this->setIfExists('contract_message', $data ?? [], null);
        $this->setIfExists('user_account_message', $data ?? [], null);
        $this->setIfExists('refund_info', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets merchant_webhook_message
     *
     * @return \OpenAPI\Client\Model\V1MerchantWebhookMessage|null
     */
    public function getMerchantWebhookMessage()
    {
        return $this->container['merchant_webhook_message'];
    }

    /**
     * Sets merchant_webhook_message
     *
     * @param \OpenAPI\Client\Model\V1MerchantWebhookMessage|null $merchant_webhook_message merchant_webhook_message
     *
     * @return self
     */
    public function setMerchantWebhookMessage($merchant_webhook_message)
    {
        if (is_null($merchant_webhook_message)) {
            throw new \InvalidArgumentException('non-nullable merchant_webhook_message cannot be null');
        }
        $this->container['merchant_webhook_message'] = $merchant_webhook_message;

        return $this;
    }

    /**
     * Gets charge_message
     *
     * @return \OpenAPI\Client\Model\V1ChargeMessage|null
     */
    public function getChargeMessage()
    {
        return $this->container['charge_message'];
    }

    /**
     * Sets charge_message
     *
     * @param \OpenAPI\Client\Model\V1ChargeMessage|null $charge_message charge_message
     *
     * @return self
     */
    public function setChargeMessage($charge_message)
    {
        if (is_null($charge_message)) {
            throw new \InvalidArgumentException('non-nullable charge_message cannot be null');
        }
        $this->container['charge_message'] = $charge_message;

        return $this;
    }

    /**
     * Gets contract_message
     *
     * @return \OpenAPI\Client\Model\V1ContractMessage|null
     */
    public function getContractMessage()
    {
        return $this->container['contract_message'];
    }

    /**
     * Sets contract_message
     *
     * @param \OpenAPI\Client\Model\V1ContractMessage|null $contract_message contract_message
     *
     * @return self
     */
    public function setContractMessage($contract_message)
    {
        if (is_null($contract_message)) {
            throw new \InvalidArgumentException('non-nullable contract_message cannot be null');
        }
        $this->container['contract_message'] = $contract_message;

        return $this;
    }

    /**
     * Gets user_account_message
     *
     * @return \OpenAPI\Client\Model\V1UserAccountMessage|null
     */
    public function getUserAccountMessage()
    {
        return $this->container['user_account_message'];
    }

    /**
     * Sets user_account_message
     *
     * @param \OpenAPI\Client\Model\V1UserAccountMessage|null $user_account_message user_account_message
     *
     * @return self
     */
    public function setUserAccountMessage($user_account_message)
    {
        if (is_null($user_account_message)) {
            throw new \InvalidArgumentException('non-nullable user_account_message cannot be null');
        }
        $this->container['user_account_message'] = $user_account_message;

        return $this;
    }

    /**
     * Gets refund_info
     *
     * @return \OpenAPI\Client\Model\V1RefundInfo|null
     */
    public function getRefundInfo()
    {
        return $this->container['refund_info'];
    }

    /**
     * Sets refund_info
     *
     * @param \OpenAPI\Client\Model\V1RefundInfo|null $refund_info refund_info
     *
     * @return self
     */
    public function setRefundInfo($refund_info)
    {
        if (is_null($refund_info)) {
            throw new \InvalidArgumentException('non-nullable refund_info cannot be null');
        }
        $this->container['refund_info'] = $refund_info;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


