<?php
/**
 * V1OnSessionPaymentErrorCode
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1OnSessionPaymentErrorCode Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1OnSessionPaymentErrorCode
{
    /**
     * Possible values of this enum
     */
    public const ON_SESSION_PAYMENT_ERROR_CODE_UNSPECIFIED = 'ON_SESSION_PAYMENT_ERROR_CODE_UNSPECIFIED';

    public const ON_SESSION_PAYMENT_ERROR_CODE_MISSING_REDIRECT_URLS = 'ON_SESSION_PAYMENT_ERROR_CODE_MISSING_REDIRECT_URLS';

    public const ON_SESSION_PAYMENT_ERROR_CODE_MISSING_REQUIRED_PARAMETERS = 'ON_SESSION_PAYMENT_ERROR_CODE_MISSING_REQUIRED_PARAMETERS';

    public const ON_SESSION_PAYMENT_ERROR_CODE_MISSING_CHARGE = 'ON_SESSION_PAYMENT_ERROR_CODE_MISSING_CHARGE';

    public const ON_SESSION_PAYMENT_ERROR_CODE_CUSTOMER_NOT_FOUND = 'ON_SESSION_PAYMENT_ERROR_CODE_CUSTOMER_NOT_FOUND';

    public const ON_SESSION_PAYMENT_ERROR_CODE_CUSTOMER_INACTIVE = 'ON_SESSION_PAYMENT_ERROR_CODE_CUSTOMER_INACTIVE';

    public const ON_SESSION_PAYMENT_ERROR_CODE_MERCHANT_CUSTOMER_ALREADY_EXISTS = 'ON_SESSION_PAYMENT_ERROR_CODE_MERCHANT_CUSTOMER_ALREADY_EXISTS';

    public const ON_SESSION_PAYMENT_ERROR_CODE_VALIDATION_FAILED = 'ON_SESSION_PAYMENT_ERROR_CODE_VALIDATION_FAILED';

    public const ON_SESSION_PAYMENT_ERROR_CODE_STRATEGY_EXECUTION_FAILED = 'ON_SESSION_PAYMENT_ERROR_CODE_STRATEGY_EXECUTION_FAILED';

    public const ON_SESSION_PAYMENT_ERROR_CODE_INVALID_PAYMENT_STRATEGY = 'ON_SESSION_PAYMENT_ERROR_CODE_INVALID_PAYMENT_STRATEGY';

    public const ON_SESSION_PAYMENT_ERROR_CODE_INTERNAL_ERROR = 'ON_SESSION_PAYMENT_ERROR_CODE_INTERNAL_ERROR';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ON_SESSION_PAYMENT_ERROR_CODE_UNSPECIFIED,
            self::ON_SESSION_PAYMENT_ERROR_CODE_MISSING_REDIRECT_URLS,
            self::ON_SESSION_PAYMENT_ERROR_CODE_MISSING_REQUIRED_PARAMETERS,
            self::ON_SESSION_PAYMENT_ERROR_CODE_MISSING_CHARGE,
            self::ON_SESSION_PAYMENT_ERROR_CODE_CUSTOMER_NOT_FOUND,
            self::ON_SESSION_PAYMENT_ERROR_CODE_CUSTOMER_INACTIVE,
            self::ON_SESSION_PAYMENT_ERROR_CODE_MERCHANT_CUSTOMER_ALREADY_EXISTS,
            self::ON_SESSION_PAYMENT_ERROR_CODE_VALIDATION_FAILED,
            self::ON_SESSION_PAYMENT_ERROR_CODE_STRATEGY_EXECUTION_FAILED,
            self::ON_SESSION_PAYMENT_ERROR_CODE_INVALID_PAYMENT_STRATEGY,
            self::ON_SESSION_PAYMENT_ERROR_CODE_INTERNAL_ERROR
        ];
    }
}


