<?php
/**
 * V1PaymentAuthorizationStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1PaymentAuthorizationStatus Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1PaymentAuthorizationStatus
{
    /**
     * Possible values of this enum
     */
    public const PAYMENT_AUTHORIZATION_STATUS_UNSPECIFIED = 'PAYMENT_AUTHORIZATION_STATUS_UNSPECIFIED';

    public const PAYMENT_AUTHORIZATION_STATUS_AUTHORIZED = 'PAYMENT_AUTHORIZATION_STATUS_AUTHORIZED';

    public const PAYMENT_AUTHORIZATION_STATUS_NOT_AUTHORIZED = 'PAYMENT_AUTHORIZATION_STATUS_NOT_AUTHORIZED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PAYMENT_AUTHORIZATION_STATUS_UNSPECIFIED,
            self::PAYMENT_AUTHORIZATION_STATUS_AUTHORIZED,
            self::PAYMENT_AUTHORIZATION_STATUS_NOT_AUTHORIZED
        ];
    }
}


