<?php
/**
 * V1WebhookEndpointStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Jamm API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * V1WebhookEndpointStatus Class Doc Comment
 *
 * @category Class
 * @description WebhookEndpointStatus is the delivery role of an endpoint.  WebhookEndpointStatus はエンドポイントの配信上の役割です。   - WEBHOOK_ENDPOINT_STATUS_LIVE: Receives production deliveries.  本番配信を受信します。  - WEBHOOK_ENDPOINT_STATUS_TEST: Receives mirrored deliveries at a candidate API version.  候補APIバージョンで複製配信を受信します。  - WEBHOOK_ENDPOINT_STATUS_DISABLED: No longer receives deliveries.  配信を受信しません。
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1WebhookEndpointStatus
{
    /**
     * Possible values of this enum
     */
    public const WEBHOOK_ENDPOINT_STATUS_UNSPECIFIED = 'WEBHOOK_ENDPOINT_STATUS_UNSPECIFIED';

    public const WEBHOOK_ENDPOINT_STATUS_LIVE = 'WEBHOOK_ENDPOINT_STATUS_LIVE';

    public const WEBHOOK_ENDPOINT_STATUS_TEST = 'WEBHOOK_ENDPOINT_STATUS_TEST';

    public const WEBHOOK_ENDPOINT_STATUS_DISABLED = 'WEBHOOK_ENDPOINT_STATUS_DISABLED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WEBHOOK_ENDPOINT_STATUS_UNSPECIFIED,
            self::WEBHOOK_ENDPOINT_STATUS_LIVE,
            self::WEBHOOK_ENDPOINT_STATUS_TEST,
            self::WEBHOOK_ENDPOINT_STATUS_DISABLED
        ];
    }
}


